plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.boccaccio0.schedule'
    compileSdk 34

    defaultConfig {
        applicationId "io.github.boccaccio0.schedule"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
        resValue "string", "app_name", "课表"
    }

    buildTypes {
        release {
            minifyEnabled false
            // 个人自用：用调试签名，免去额外配置密钥库
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
